### ISSUE TITLE
Trying to compile with input headers

### ISSUE THREAD

**Issue by jorgevazquezperez** [pocl/pocl#1215]
I am trying to compile this kernel with the `clCompileProgram` function:
```
#include <cppsim/state.hpp>
#include <cppsim/circuit.hpp>
#include <cppsim/observable.hpp>
#include <cppsim/gate_factory.hpp>

// Define the kernel function
__kernel void run_circuit(__global std::complex<double>* result) {
    // Create a quantum state with 1 qubit
    int n = 1;
    QuantumState state(n);
    state.set_zero_state();

    // Perform a Hadamard gate on qubit 0
    int target_qubit = 0;
    //QuantumGateBase* hadamard_gate = gate::H(target_qubit);
    //hadamard_gate->update_quantum_state(&state);
    auto x_gate = gate::X(target_qubit);
    x_gate->update_quantum_state(&state);

    std::string Pauli_string = "Z 0";

    double coef = 1.0;
    Observable observable(n);
    observable.add_operator(coef, Pauli_string.c_str());

    // Calculate and print the expectation value
    result = observable.get_expectation_value(&state);
    //std::cout << "Expectation value of Pauli-Z: " << result << std::endl;
}
```

What I do in the host program is the following:

```
    const char *cppsim_state_header_source = read_source("../qulacs/include/cppsim/state.hpp");
    cl_program cppsim_state_pg = clCreateProgramWithSource(context,
                                                           1, &cppsim_state_header_source, NULL, &err);
    const char *cppsim_circuit_header_source = read_source("../qulacs/include/cppsim/circuit.hpp");
    cl_program cppsim_circuit_pg = clCreateProgramWithSource(context,
                                                             1, &cppsim_circuit_header_source, NULL, &err);
    const char *cppsim_observable_header_source = read_source("../qulacs/include/cppsim/observable.hpp");
    cl_program cppsim_observable_pg = clCreateProgramWithSource(context,
                                                                1, &cppsim_observable_header_source, NULL, &err);
    const char *cppsim_gate_factory_header_source = read_source("../qulacs/include/cppsim/gate_factory.hpp");
    cl_program cppsim_gate_factory_pg = clCreateProgramWithSource(context,
                                                                  1, &cppsim_gate_factory_header_source, NULL, &err);

    // lets assume the program source described above is given
    // by program_A and is loaded via clCreateProgramWithSource
    int num_input_headers = 4;
    cl_program input_headers[num_input_headers] = {
        cppsim_state_pg,
        cppsim_circuit_pg,
        cppsim_observable_pg,
        cppsim_gate_factory_pg};
    const char *input_header_names[num_input_headers] = {
        "cppsim/state.hpp",
        "cppsim/circuit.hpp",
        "cppsim/observable.hpp",
        "cppsim/gate_factory.hpp"};

    const char *includes =  "-I../qulacs/include ";

    err = clCompileProgram(program,
                           1, &device_id, // num_devices & device_list
                           includes,      // compile_options
                           num_input_headers,             // num_input_headers
                           input_headers,
                           input_header_names,
                           NULL, NULL); // pfn_notify & user_data
```

But this compilation always fails giving as an error that one of the headers inside of the Qulacs ones is missing. If I add a "-I" option with the path to that header it pops with another one. And this is non stoping and I do not know why Clang and LLVM don't find these headers by themselves. 

PD: I am using CLang and LLVM 15.0.2 and PoCL 3.1. Moreover, the device that I am trying to compile the kernel on is pthread.

**Comment by pjaaskel** [comment]
I've fixed some include-related in the master branch, so please test with the latest master and let's see if it solves your problem.

**Comment by jorgevazquezperez** [comment]
I tried with the latest version of all the libraries (the master branch on PoCL and version 16 of LLVM and Clang) and the same problem remains. I always get stuck in the `#include_next <math.h>` in the math.h file.

**Comment by pjaaskel** [comment]
Hm, math and cmath sound like host C/C++ compiler headers. Are you sure you want to include them in the device side?

**Comment by pjaaskel** [comment]
If you can send a reproducer, I can try to fix this. I thought I covered all the -I problems already, but could be not.

**Comment by jorgevazquezperez** [comment]
I realize I was missunderstanding the problem, all good now.
