### ISSUE TITLE
Crash with "error: Invalid record" on LLVM 3.7rc2

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#231]
When I use 75d64c6f5 with Debian's LLVM 3.7rc2 to run this program:

https://gist.github.com/inducer/b5d412b2a7f8b34b9770

pocl (or LLVM likely) exits the program with code 1 and says

```
error: Invalid record
```

on stderr. The same pocl on LLVM 3.6 compiles this fine. By the way, I'm not claiming that this code does anything meaningful. It is just a very reduced example of the scan code in PyOpenCL, whose failure with the same error prompted me to file this bug report.

**Comment by pjaaskel** [comment]
This seems like the same issue that was fixed with the TAS disabling revision. At least it doesn't crash for me and returns code 0.

**Comment by inducer** [comment]
Weird. Still crashes for me. Can you try and clear both pocl's and pyopencl's cache?

```
clcache()
{
  rm -Rf ~/.cache/pocl
  rm -Rf ~/.cache/pytools
}
```

I made another reduced version:

https://gist.github.com/inducer/0ed8edddb5fb2545a6be

**Comment by pjaaskel** [comment]
No difference (there was no pytools cache). Also tried the other reduced version.

**Comment by inducer** [comment]
Rebuilt pocl on top of a debug build of LLVM. This is what happens: (with `scan-test-2.py`)

```
python: /home/andreas/pack/llvm/lib/IR/Instructions.cpp:239: void llvm::CallInst::init(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&): Assertion `(i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"' failed.
```

**Comment by inducer** [comment]
This is the associated backtrace:

```
#0  0x00007ffff6f28107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6f294e8 in __GI_abort () at abort.c:89
#2  0x00007ffff6f21226 in __assert_fail_base (fmt=0x7ffff7057d08 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7fffcdfc1638 "(i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && \"Calling a function with a bad signature!\"", 
    file=file@entry=0x7fffcdfc1500 "/home/andreas/pack/llvm/lib/IR/Instructions.cpp", line=line@entry=239, 
    function=function@entry=0x7fffcdfc4b60 <llvm::CallInst::init(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&)::__PRETTY_FUNCTION__> "void llvm::CallInst::init(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&)") at assert.c:92
#3  0x00007ffff6f212d2 in __GI___assert_fail (
    assertion=0x7fffcdfc1638 "(i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && \"Calling a function with a bad signature!\"", 
    file=0x7fffcdfc1500 "/home/andreas/pack/llvm/lib/IR/Instructions.cpp", line=239, 
    function=0x7fffcdfc4b60 <llvm::CallInst::init(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::Twine const&)::__PRETTY_FUNCTION__> "void llvm::CallInst::init(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&)") at assert.c:101
#4  0x00007fffcde48d8c in llvm::CallInst::init (this=0x47e4418, FTy=0xfaf3d8, Func=0x47e48a8, Args=..., NameStr=...) at /home/andreas/pack/llvm/lib/IR/Instructions.cpp:237
#5  0x00007fffcdca69d9 in llvm::CallInst::CallInst (this=0x47e4418, Ty=0xfaf3d8, Func=0x47e48a8, Args=..., NameStr=..., InsertBefore=0x0)
    at /home/andreas/pack/llvm/include/llvm/IR/Instructions.h:1711
#6  0x00007fffcdca6853 in llvm::CallInst::Create (Ty=0xfaf3d8, Func=0x47e48a8, Args=..., NameStr=..., InsertBefore=0x0)
    at /home/andreas/pack/llvm/include/llvm/IR/Instructions.h:1402
#7  0x00007fffcdcf3605 in llvm::CallInst::Create (Func=0x47e48a8, Args=..., NameStr=..., InsertBefore=0x0) at /home/andreas/pack/llvm/include/llvm/IR/Instructions.h:1396
#8  0x00007fffcde385a1 in createCallHelper (Callee=0x47e48a8, Ops=..., Builder=0x7fffffffb398, Name=...) at /home/andreas/pack/llvm/lib/IR/IRBuilder.cpp:62
#9  0x00007fffcde393b1 in llvm::IRBuilderBase::CreateMaskedIntrinsic (this=0x7fffffffb398, Id=<incomplete type>, Ops=..., DataTy=0xf66810, Name=...)
    at /home/andreas/pack/llvm/lib/IR/IRBuilder.cpp:247
#10 0x00007fffcde39264 in llvm::IRBuilderBase::CreateMaskedLoad (this=0x7fffffffb398, Ptr=0x47e4818, Align=4, Mask=0x47e4720, PassThru=0x12e9a40, Name=...)
    at /home/andreas/pack/llvm/lib/IR/IRBuilder.cpp:222
#11 0x00007fffd261e7e5 in (anonymous namespace)::InnerLoopVectorizer::vectorizeMemoryInstruction (this=0x7fffffffb350, Instr=0x4799978)
    at /home/andreas/pack/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:2293
#12 0x00007fffd26243c5 in (anonymous namespace)::InnerLoopVectorizer::vectorizeBlockInLoop (this=0x7fffffffb350, BB=0x4799770, PV=0x7fffffffb0a0)
    at /home/andreas/pack/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:3563
#13 0x00007fffd2621b16 in (anonymous namespace)::InnerLoopVectorizer::vectorizeLoop (this=0x7fffffffb350)
    at /home/andreas/pack/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:3052
#14 0x00007fffd261797e in (anonymous namespace)::InnerLoopVectorizer::vectorize (this=0x7fffffffb350, L=0x7fffffffb660)
    at /home/andreas/pack/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:280
#15 0x00007fffd261b896 in (anonymous namespace)::LoopVectorize::processLoop (this=0x47468f0, L=0x4795f60)
    at /home/andreas/pack/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:1679
#16 0x00007fffd261a65a in (anonymous namespace)::LoopVectorize::runOnFunction (this=0x47468f0, F=...) at /home/andreas/pack/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp:1492
#17 0x00007fffcde78c0f in llvm::FPPassManager::runOnFunction (this=0x4743f60, F=...) at /home/andreas/pack/llvm/lib/IR/LegacyPassManager.cpp:1520
#18 0x00007fffcde78d6e in llvm::FPPassManager::runOnModule (this=0x4743f60, M=...) at /home/andreas/pack/llvm/lib/IR/LegacyPassManager.cpp:1540
#19 0x00007fffcde7909d in (anonymous namespace)::MPPassManager::runOnModule (this=0x3975810, M=...) at /home/andreas/pack/llvm/lib/IR/LegacyPassManager.cpp:1596
#20 0x00007fffcde796fe in llvm::legacy::PassManagerImpl::run (this=0x3975480, M=...) at /home/andreas/pack/llvm/lib/IR/LegacyPassManager.cpp:1698
#21 0x00007fffcde79903 in llvm::legacy::PassManager::run (this=0x3975460, M=...) at /home/andreas/pack/llvm/lib/IR/LegacyPassManager.cpp:1729
#22 0x00007fffe2797996 in pocl_llvm_generate_workgroup_function (device=<optimized out>, kernel=kernel@entry=0xf6b380, local_x=local_x@entry=16, local_y=local_y@entry=1, 
    local_z=local_z@entry=1) at pocl_llvm_api.cc:1377
#23 0x00007fffe2780e8b in POclEnqueueNDRangeKernel (command_queue=0xf3f110, kernel=0xf6b380, work_dim=1, global_work_offset=<optimized out>, global_work_size=<optimized out>, 
    local_work_size=<optimized out>, num_events_in_wait_list=0, event_wait_list=0x0, event=0x7fffffffd148) at clEnqueueNDRangeKernel.c:240
#24 0x00007fffea2abbf4 in _call_func<int (*)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**), 0, 1, 2, 3, 4, 5, 6, 7, 8, _cl_command_queue* const&, _cl_kernel* const&, unsigned int&, unsigned long const*&, unsigned long const*&, unsigned long const*&, unsigned long, _cl_event**, _cl_event**> (args=..., func=<optimized out>) at src/c_wrapper/function.h:38
#25 call_tuple<int (*&)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**), std::tuple<_cl_command_queue* const&, _cl_kernel* const&, unsigned int&, unsigned long const*&, unsigned long const*&, unsigned long const*&, unsigned long, _cl_event**, _cl_event**> > (args=<optimized out>, func=<synthetic pointer>) at src/c_wrapper/function.h:49
#26 call<__CLArgGetter, int (*)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**)> (func=<optimized out>, this=0x7fffffffd1a0) at src/c_wrapper/function.h:108
#27 clcall<int (*)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**)>
    (name=0x7fffea2b0508 "clEnqueueNDRangeKernel", func=<optimized out>, this=0x7fffffffd1a0) at src/c_wrapper/error.h:186
#28 call_guarded<command_queue*&, kernel*&, unsigned int&, unsigned long const*&, unsigned long const*&, unsigned long const*&, pyopencl_buf<_cl_event*> const&, _CLObjOutArg<event>, _cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**> (
    name=0x7fffea2b0508 "clEnqueueNDRangeKernel", func=<optimized out>) at src/c_wrapper/error.h:218
#29 operator() (__closure=<synthetic pointer>) at src/c_wrapper/kernel.cpp:180
#30 retry_mem_error<enqueue_nd_range_kernel(clbase**, clobj_t, clobj_t, cl_uint, const size_t*, const size_t*, const size_t*, clbase* const*, uint32_t)::<lambda()> > (func=...)
    at src/c_wrapper/error.h:294
#31 operator() (__closure=<synthetic pointer>) at src/c_wrapper/error.h:307
#32 c_handle_error<c_handle_retry_mem_error(Func&&) [with Func = enqueue_nd_range_kernel(clbase**, clobj_t, clobj_t, cl_uint, const size_t*, const size_t*, const size_t*, clbase* const*, uint32_t)::<lambda()>]::<lambda()> > (func=...) at src/c_wrapper/error.h:271
#33 c_handle_retry_mem_error<enqueue_nd_range_kernel(clbase**, clobj_t, clobj_t, cl_uint, const size_t*, const size_t*, const size_t*, clbase* const*, uint32_t)::<lambda()> > (
    func=<optimized out>) at src/c_wrapper/error.h:307
#34 enqueue_nd_range_kernel (evt=0x7fffcc265878, _queue=<optimized out>, _knl=0xf63ec0, work_dim=work_dim@entry=1, global_work_offset=0x0, global_work_size=0x7fffffffd2e0, 
    local_work_size=0x7fffffffd2c0, _wait_for=0x0, num_wait_for=0) at src/c_wrapper/kernel.cpp:181
#35 0x00007fffea261fe2 in _cffi_f_enqueue_nd_range_kernel (self=<optimized out>, args=<optimized out>) at build/temp.linux-x86_64-2.7/pyopencl._cffi.cpp:4541
#36 0x00000000004c9ae5 in PyEval_EvalFrameEx ()
#37 0x00000000004c8329 in PyEval_EvalCodeEx ()
#38 0x00000000004c9ff6 in PyEval_EvalFrameEx ()
#39 0x00000000004e42d0 in ?? ()
#40 0x00000000004cd352 in PyEval_EvalFrameEx ()
#41 0x00000000004e42d0 in ?? ()
#42 0x0000000000502608 in ?? ()
#43 0x000000000056ef6b in ?? ()
#44 0x00000000004ca803 in PyEval_EvalFrameEx ()
#45 0x00000000004ca272 in PyEval_EvalFrameEx ()
#46 0x00000000004c8329 in PyEval_EvalCodeEx ()
#47 0x000000000050111f in ?? ()
#48 0x00000000004f6e22 in PyRun_FileExFlags ()
#49 0x00000000004f5f17 in PyRun_SimpleFileExFlags ()
#50 0x0000000000497afd in Py_Main ()
#51 0x00007ffff6f14b45 in __libc_start_main (main=0x497590 <main>, argc=2, argv=0x7fffffffe278, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffe268) at libc-start.c:287
#52 0x00000000004974b8 in _start ()
```

**Comment by inducer** [comment]
Btw, I saw that pocl (correctly) detected my CPU as 'broadwell'. If that has any consequences, then this may explain why I'm seeing this and you are not. Especially since this seems to be something to do with emitting vector intrinsics.

**Comment by pjaaskel** [comment]
Yes. My guess it's something to do with the new gather load generation in latest LLVM vectorizer.

**Comment by pjaaskel** [comment]
We might want to check if it's possible to avoid using the fake-addr-space map altogether now for single-AS targets. Using the fake ids during optimization seems to constantly call for trouble.

**Comment by pjaaskel** [comment]
This is not easy do to the SPIR which has multiple address spaces. So we either need to fix the TAS for all cases (which might turn out impossible at the end due to intrinsics for which it should find versions with correct address spaces) or then let the frontend flatten the AS early which causes problems in the argument AS detection and removes the benefits of disjoint address space alias analysis.

**Comment by inducer** [comment]
This still happens if I configure with `LLC_HOST_CPU=x86-64`. Is there some way to work around this, i.e. to disable the breaking optimization pass for the moment?

**Comment by pjaaskel** [comment]
Try export POCL_WORK_GROUP_METHOD=loops. This should disable vectorization which of course means much worse performance.

**Comment by inducer** [comment]
Awesome. `export POCL_WORK_GROUP_METHOD=loops` gives me a working CL implementation for now. Thanks very much!

**Comment by inducer** [comment]
Ugh, I lied. It is still possible to get "Invalid record" even with `export POCL_WORK_GROUP_METHOD=loops`. Irritatingly, this particular instance of the problem *disappears* as soon as you build LLVM and pocl with assertions turned on.

Here's the kernel that provokes that for me:
https://gist.github.com/inducer/3a396cb1fcd07df9dcb6

If you need a reduced version of that, just let me know.

**Comment by inducer** [comment]
Oops. I actually lost track of where pyopencl keeps its cache. It's actually in `~/.cache/pyopencl`. FWIW, I use this shell function to blow away all caches I'm aware of:

```
clcache()
{
  rm -Rf ~/.pocl
  rm -Rf ~/.cache/pocl
  rm -Rf ~/.cache/pytools
  rm -Rf ~/.cache/pyopencl/
}
```

**Comment by pjaaskel** [comment]
This is rather painful. I thought I'd fix this by just looking at the kernel metadata in LLVM instead of using the fake address space ids which confuse the vectorizer and other passes, but it turned out that the 'kernel_arg_addr_space' metadata has the _target_ ids (how useful is that??), not some generic OpenCL ids (such as SPIR ones).  

Options: 1) Try to propose a patch to LLVM to use logical ids in the metadata. This might not go through if someone relies on this weird semantics, probably won't make it to LLVM 3.7.x in any case. 2) Parse the function argument address spaces from the OpenCL C sources (and perhaps convert to an own metadata to store in LLVM bitcode). This seems like an overkill thing to do just to get the address spaces and SPIR input would still be a problem. 3) Use fake ids, but apply TAS very early in the process, maintaining the function argument address spaces in custom metadata or similar. Option 3) sounds best as it would fix SPIR input in the same shot.

**Comment by pjaaskel** [comment]
Can you try this branch: https://github.com/pocl/pocl/tree/early-as-flattening if it makes any difference to this case and whether the other case starts to break again.

**Comment by inducer** [comment]
With assertions off: Crashes with a segfault here.

```
#0  0x00007fffda5fcd13 in (anonymous namespace)::BitcodeReader::parseFunctionBody(llvm::Function*) [clone .constprop.832] ()
   from /home/andreas/pack/llvm-build-release/lib/libLLVMBitReader.so.3.7
#1  0x00007fffda5feef3 in (anonymous namespace)::BitcodeReader::materialize(llvm::GlobalValue*) [clone .part.820] ()
   from /home/andreas/pack/llvm-build-release/lib/libLLVMBitReader.so.3.7
#2  0x00007fffda5ff44a in (anonymous namespace)::BitcodeReader::materializeModule(llvm::Module*) () from /home/andreas/pack/llvm-build-release/lib/libLLVMBitReader.so.3.7
#3  0x00007fffd92aac9c in llvm::Module::materializeAll() () from /home/andreas/pack/llvm-build-release/lib/libLLVMCore.so.3.7
#4  0x00007fffd92aacc9 in llvm::Module::materializeAllPermanently() () from /home/andreas/pack/llvm-build-release/lib/libLLVMCore.so.3.7
#5  0x00007fffda5ffd96 in getBitcodeModuleImpl(std::unique_ptr<llvm::DataStreamer, std::default_delete<llvm::DataStreamer> >, llvm::StringRef, (anonymous namespace)::BitcodeReader*, llvm::LLVMContext&, bool, bool) [clone .constprop.828] () from /home/andreas/pack/llvm-build-release/lib/libLLVMBitReader.so.3.7
#6  0x00007fffda601134 in llvm::parseBitcodeFile(llvm::MemoryBufferRef, llvm::LLVMContext&, std::function<void (llvm::DiagnosticInfo const&)>) ()
   from /home/andreas/pack/llvm-build-release/lib/libLLVMBitReader.so.3.7
#7  0x00007fffdf8ad486 in llvm::parseIR(llvm::MemoryBufferRef, llvm::SMDiagnostic&, llvm::LLVMContext&) () from /home/andreas/pack/llvm-build-release/lib/libLLVMIRReader.so.3.7
#8  0x00007fffdf8add57 in llvm::parseIRFile(llvm::StringRef, llvm::SMDiagnostic&, llvm::LLVMContext&) () from /home/andreas/pack/llvm-build-release/lib/libLLVMIRReader.so.3.7
#9  0x00007fffe102849a in ParseIRFile (fname=fname@entry=0x7fffffff70c0 "/home/andreas/.cache/pocl/kcache/FP/ANFACJOOPBHLGKOGHFMHBHDGOJLENIEHKGBMA/generate/16-1-1/parallel.bc", 
    Err=..., ctx=...) at pocl_llvm_api.cc:188
#10 0x00007fffe1030969 in pocl_llvm_codegen (kernel=kernel@entry=0x34d2400, device=device@entry=0x2ac1c00, 
    infilename=infilename@entry=0x7fffffff70c0 "/home/andreas/.cache/pocl/kcache/FP/ANFACJOOPBHLGKOGHFMHBHDGOJLENIEHKGBMA/generate/16-1-1/parallel.bc", 
    outfilename=outfilename@entry=0x7fffffff74c0 "/home/andreas/.cache/pocl/kcache/FP/ANFACJOOPBHLGKOGHFMHBHDGOJLENIEHKGBMA/generate/16-1-1/generate.so.o")
    at pocl_llvm_api.cc:1524
#11 0x00007fffe1025a3a in llvm_codegen (tmpdir=0xefb150 "/home/andreas/.cache/pocl/kcache/FP/ANFACJOOPBHLGKOGHFMHBHDGOJLENIEHKGBMA/generate/16-1-1", kernel=0x34d2400, 
    device=0x2ac1c00) at common.c:87
#12 0x00007fffe1027709 in check_compiler_cache (cmd=0xee5e20) at basic.c:902
#13 0x00007fffe101b13f in exec_commands (node_list=0xee5e20) at clFinish.c:111
#14 POclFinish (command_queue=command_queue@entry=0x2b43fa0) at clFinish.c:93
#15 0x00007fffe101bfb5 in POclFlush (command_queue=command_queue@entry=0x2b43fa0) at clFlush.c:35
#16 0x00007fffe100f635 in POclReleaseCommandQueue (command_queue=0x2b43fa0) at clReleaseCommandQueue.c:34
#17 0x00007fffe101cd97 in POclReleaseEvent (event=0x34c7a10) at clReleaseEvent.c:41
#18 0x00007fffe9218149 in _call_func<int (*)(_cl_event*), 0, _cl_event* const&> (args=..., func=<optimized out>) at src/c_wrapper/function.h:38
#19 call_tuple<int (*&)(_cl_event*), std::tuple<_cl_event* const&> > (args=<optimized out>, func=<synthetic pointer>) at src/c_wrapper/function.h:49
#20 call<__CLArgGetter, int (*)(_cl_event*)> (func=<optimized out>, this=<synthetic pointer>) at src/c_wrapper/function.h:108
#21 clcall<int (*)(_cl_event*)> (name=0x7fffe924275a "clReleaseEvent", func=<optimized out>, this=<synthetic pointer>) at src/c_wrapper/error.h:186
#22 call_guarded_cleanup<_cl_event*, event*> (name=0x7fffe924275a "clReleaseEvent", func=<optimized out>) at src/c_wrapper/error.h:256
#23 event::~event (this=0x56a4ff0, __in_chrg=<optimized out>) at src/c_wrapper/event.cpp:109
#24 0x00007fffe92183d9 in event::~event (this=0x56a4ff0, __in_chrg=<optimized out>) at src/c_wrapper/event.cpp:110
#25 0x00007fffe91fabcc in _cffi_f_clobj__delete (self=<optimized out>, arg0=0x7fffd7612a08) at build/temp.linux-x86_64-2.7/pyopencl._cffi.cpp:1316
#26 0x00000000004cab1e in PyEval_EvalFrameEx ()
```

**Comment by inducer** [comment]
With assertions on:

```
python: /home/andreas/pack/llvm/lib/Bitcode/Writer/ValueEnumerator.h:131: unsigned int llvm::ValueEnumerator::getTypeID(llvm::Type*) const: Assertion `I != TypeMap.end() && "Type not in ValueEnumerator!"' failed.
```

Backtrace:

```
#0  0x00007ffff6f28107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6f294e8 in __GI_abort () at abort.c:89
#2  0x00007ffff6f21226 in __assert_fail_base (fmt=0x7ffff7057d08 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7fffdf995830 "I != TypeMap.end() && \"Type not in ValueEnumerator!\"", 
    file=file@entry=0x7fffdf9957c0 "/home/andreas/pack/llvm/lib/Bitcode/Writer/ValueEnumerator.h", line=line@entry=131, 
    function=function@entry=0x7fffdf9991a0 <llvm::ValueEnumerator::getTypeID(llvm::Type*) const::__PRETTY_FUNCTION__> "unsigned int llvm::ValueEnumerator::getTypeID(llvm::Type*) const") at assert.c:92
#3  0x00007ffff6f212d2 in __GI___assert_fail (assertion=0x7fffdf995830 "I != TypeMap.end() && \"Type not in ValueEnumerator!\"", 
    file=0x7fffdf9957c0 "/home/andreas/pack/llvm/lib/Bitcode/Writer/ValueEnumerator.h", line=131, 
    function=0x7fffdf9991a0 <llvm::ValueEnumerator::getTypeID(llvm::Type*) const::__PRETTY_FUNCTION__> "unsigned int llvm::ValueEnumerator::getTypeID(llvm::Type*) const")
    at assert.c:101
#4  0x00007fffdf9645b6 in llvm::ValueEnumerator::getTypeID (this=0x7fffffff6260, T=0x38a97c0) at /home/andreas/pack/llvm/lib/Bitcode/Writer/ValueEnumerator.h:131
#5  0x00007fffdf9601ab in WriteInstruction (I=..., InstID=135, VE=..., Stream=..., Vals=...) at /home/andreas/pack/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp:1979
#6  0x00007fffdf960b99 in WriteFunction (F=..., VE=..., Stream=...) at /home/andreas/pack/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp:2136
#7  0x00007fffdf96210e in WriteModule (M=0x66b9110, Stream=..., ShouldPreserveUseListOrder=false) at /home/andreas/pack/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp:2401
#8  0x00007fffdf96247c in llvm::WriteBitcodeToFile (M=0x66b9110, Out=..., ShouldPreserveUseListOrder=false) at /home/andreas/pack/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp:2502
#9  0x00007fffe10468cd in pocl_write_module (module=module@entry=0x66b9110, 
    path=path@entry=0x7fffffff6660 "/home/andreas/.cache/pocl/kcache/IB/MHOEDMDCLLFHPIILIHKLLNMECCGBMHGKJBFBJ/generate/16-1-1/parallel.bc", dont_rewrite=dont_rewrite@entry=0)
    at LLVMFileUtils.cc:277
#10 0x00007fffe100e4c0 in pocl_cache_write_kernel_parallel_bc (bc=bc@entry=0x66b9110, program=program@entry=0x145d9e0, device_i=device_i@entry=0, kernel=kernel@entry=0x66af670, 
    local_x=local_x@entry=16, local_y=local_y@entry=1, local_z=1) at pocl_cache.c:278
#11 0x00007fffe10169cf in pocl_llvm_generate_workgroup_function (device=<optimized out>, kernel=kernel@entry=0x66af670, local_x=local_x@entry=16, local_y=local_y@entry=1, 
    local_z=local_z@entry=1) at pocl_llvm_api.cc:1381
#12 0x00007fffe0fffe9b in POclEnqueueNDRangeKernel (command_queue=0x2b461c0, kernel=0x66af670, work_dim=1, global_work_offset=<optimized out>, global_work_size=<optimized out>, 
    local_work_size=<optimized out>, num_events_in_wait_list=0, event_wait_list=0x0, event=0x7fffffff7c08) at clEnqueueNDRangeKernel.c:240
#13 0x00007fffe923ebf4 in _call_func<int (*)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**), 0, 1, 2, 3, 4, 5, 6, 7, 8, _cl_command_queue* const&, _cl_kernel* const&, unsigned int&, unsigned long const*&, unsigned long const*&, unsigned long const*&, unsigned long, _cl_event**, _cl_event**> (args=..., func=<optimized out>) at src/c_wrapper/function.h:38
#14 call_tuple<int (*&)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**), std::tuple<_cl_command_queue* const&, _cl_kernel* const&, unsigned int&, unsigned long const*&, unsigned long const*&, unsigned long const*&, unsigned long, _cl_event**, _cl_event**> > (args=<optimized out>, func=<synthetic pointer>) at src/c_wrapper/function.h:49
#15 call<__CLArgGetter, int (*)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**)> (func=<optimized out>, this=0x7fffffff7c60) at src/c_wrapper/function.h:108
#16 clcall<int (*)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**)>
    (name=0x7fffe9243508 "clEnqueueNDRangeKernel", func=<optimized out>, this=0x7fffffff7c60) at src/c_wrapper/error.h:186
#17 call_guarded<command_queue*&, kernel*&, unsigned int&, unsigned long const*&, unsigned long const*&, unsigned long const*&, pyopencl_buf<_cl_event*> const&, _CLObjOutArg<event>, _cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**> (
    name=0x7fffe9243508 "clEnqueueNDRangeKernel", func=<optimized out>) at src/c_wrapper/error.h:218
#18 operator() (__closure=<synthetic pointer>) at src/c_wrapper/kernel.cpp:180
#19 retry_mem_error<enqueue_nd_range_kernel(clbase**, clobj_t, clobj_t, cl_uint, const size_t*, const size_t*, const size_t*, clbase* const*, uint32_t)::<lambda()> > (func=...)
    at src/c_wrapper/error.h:294
#20 operator() (__closure=<synthetic pointer>) at src/c_wrapper/error.h:307
#21 c_handle_error<c_handle_retry_mem_error(Func&&) [with Func = enqueue_nd_range_kernel(clbase**, clobj_t, clobj_t, cl_uint, const size_t*, const size_t*, const size_t*, clbase* const*, uint32_t)::<lambda()>]::<lambda()> > (func=...) at src/c_wrapper/error.h:271
#22 c_handle_retry_mem_error<enqueue_nd_range_kernel(clbase**, clobj_t, clobj_t, cl_uint, const size_t*, const size_t*, const size_t*, clbase* const*, uint32_t)::<lambda()> > (
    func=<optimized out>) at src/c_wrapper/error.h:307
#23 enqueue_nd_range_kernel (evt=0x7fffca76d840, _queue=<optimized out>, _knl=0x4352c30, work_dim=work_dim@entry=1, global_work_offset=0x0, global_work_size=0x7fffffff7d80, 
    local_work_size=0x0, _wait_for=0x0, num_wait_for=0) at src/c_wrapper/kernel.cpp:181
#24 0x00007fffe91f4fe2 in _cffi_f_enqueue_nd_range_kernel (self=<optimized out>, args=<optimized out>) at build/temp.linux-x86_64-2.7/pyopencl._cffi.cpp:4541
```

**Comment by pjaaskel** [comment]
OK. Getting difficult without a local haswell. Are you able to provide an account on one to speed the debugging of this? I'll try to ask for it here locally also.

**Comment by pjaaskel** [comment]
Ah you had Broadwell, even harder to find one locally.

**Comment by inducer** [comment]
And that Broadwell machine is my personal laptop, which I use to roam around all day, so giving you access is tricky. I have some Haswell boxes on order that should show up in the next week or two. If the problem occurs there, too, I could give you access to those. Will let you know.

**Comment by jrprice** [comment]
Reproduced this error on a Haswell box, which @pjaaskel now has access to. Here's a C++ reproducer, since we don't have PyOpenCL available currently.

https://gist.github.com/jrprice/d16d82d5dfdcd953aedd

**Comment by pjaaskel** [comment]
Thanks! Now all I need is some more time to look into this :)

**Comment by pjaaskel** [comment]
I fixed this by (once again) making x86_64 to also flatten the address spaces in TAS. Maybe this introduces some other regressions, but we need to fix them one by one, I suppose.  Can I add this test to the MIT-licensed regression test suite of pocl?

**Comment by inducer** [comment]
> Can I add this test to the MIT-licensed regression test suite of pocl?

If you're referring to anything I've posted, sure. Thanks for your help! I'll take a look tomorrow.

**Comment by pjaaskel** [comment]
OK thanks. James did the wrapping, but I assumed it's OK from his side also to add it.

**Comment by jrprice** [comment]
Fine with me. My version passes uninitialised arguments to the kernel enqueue though so might cause unrelated crashes depending on how pocl handles that.
