### ISSUE TITLE
[pyopencl regression] finalize_kernel_command: Assertion `(*(&k->cmd->event))->status == 0x1' failed

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#324]
On 14d9bbd

```
PYOPENCL_TEST=port python 'test_algorithm.py' 'test_elwise_kernel(cl._csc)'
```

now gives me

```
python: pthread_scheduler.c:277: finalize_kernel_command: Assertion `(*(&k->cmd->event))->status == 0x1' failed.
[1]    13021 abort      PYOPENCL_TEST=port python 'test_algorithm.py' 'test_elwise_kernel(cl._csc)'
```

**Comment by vkorhonen** [comment]
I could not reproduce this. Quickly browsing through commit log, nothing indicates that anyone has done anything about it thou.

**Comment by pjaaskel** [comment]
Me neither. Perhaps some transitional bug fixed by some unrelated bugfix. @inducer please reopen if still breaks for you.

**Comment by inducer** [comment]
Not fixed for me (using Debian's LLVM)--although the message has changed:
```
PYOPENCL_TEST=port python 'test_algorithm.py' 'test_elwise_kernel(cl._csc)'
error: Invalid cast (Producer: 'LLVM3.8.1' Reader: 'LLVM 3.8.1')
```

**Comment by inducer** [comment]
(Somehow there's no "reopen" button, otherwise I'd use it.)

**Comment by pjaaskel** [comment]
This looks like a different issue entirely. The previous one was in the runtime, now it seems more like a corrupted IR. It can happen if you have an LLVM without assertions; it manages to write a corrupted bitcode (with invalid casts) but fails when trying to read it back. 

Please try upgrading to LLVM 3.9 and see if it works. We focus on the latest version as our group has limited resources to work on the older ones.

**Comment by inducer** [comment]
No essential difference:

```
error: Invalid cast (Producer: 'LLVM3.9.0' Reader: 'LLVM 3.9.0')
```

**Comment by inducer** [comment]
This seems to be happening for a fair number of tests, FWIW. The test suite does not get very far without hitting this.

**Comment by vkorhonen** [comment]
Could this be related to pyopencl cache? Have you disabled and destroyed pyopencl cache?

**Comment by pjaaskel** [comment]
@inducer also, if you can find the parallel.bc/program.bc, can you llvm-dis it or does llvm-dis crash also?

**Comment by inducer** [comment]
Nope, this happens for me even with a cleared cache.
```
$ llvm-dis-3.9 ~/.cache/pocl/kcache/IF/EJFFFOGEMCGNBFIPEPGFEAECNJFEFPANMNLPF/generate/0-0-0/parallel.bc
llvm-dis-3.9: error: Invalid cast (Producer: 'LLVM3.9.0' Reader: 'LLVM 3.9.0')
```

https://tiker.net/tmp/parallel.bc

**Comment by pjaaskel** [comment]
Yup, it's corrupted.
```
./local/stow/llvm-3.9-debug/bin/llvm-dis parallel.bc 
../local/stow/llvm-3.9-debug/bin/llvm-dis: error: Invalid cast (Producer: 'LLVM3.9.0' Reader: 'LLVM 3.9.1')
```

You probably don't have an asserts-on build, do you? The usual suspect is the TargetAddressSpaces pass that might produce your corrupted output which assertions do not catch which is then fails at load time. I'm working on a branch to get rid of TAS.  I hopefully have soon something ready for testing. 

If you wish, you can already patch your LLVM with a required patch that can be downloaded from here: https://reviews.llvm.org/file/data/ij7j4otyjpwrkjaqceb5/PHID-FILE-s5473rljfaxxygujquop/D26157.diff  This should apply cleanly to 3.9, probably also 3.8.

**Comment by inducer** [comment]
Don't have one, no. I'm super short-handed at the moment, so it may be a while until I can do a build.

**Comment by pjaaskel** [comment]
OK. I've pushed changes that should allow building pocl without the fake address spaces if you have patched your clang with the above patch.

**Comment by inducer** [comment]
Thanks for working on this. I just built a patched clang and this, and it looks like things get a bit further now. I've reported the things I've run into so far. There's also still what appears to be some cache-related crashiness left, but I wasn't able to pin that down exactly yet.

**Comment by inducer** [comment]
Thanks for working on this. I just built a patched clang and this, and it looks like things get a bit further now. I've reported the things I've run into so far. There's also still what appears to be some cache-related crashiness left, but I wasn't able to pin that down exactly yet.
