### ISSUE TITLE
relocation error with pocl 1.2 on top of Clang 7.0.1 (but not with Clang 6.0.1)

### ISSUE THREAD

**Issue by boegel** [pocl/pocl#694]
After building `pocl` 1.2 from source on top of Clang 7.0.1, I ran into errors like this when trying to *run* some simple OpenCL examples (for example https://github.com/rsnemmen/OpenCL-examples/tree/master/mandelbrot).

Here's the output with `POCL_DEBUG=1` set:

```
...
Load kernel
[2019-01-15 17:23:58.119082783] POCL: in fn compile_and_link_program at line 511:
  *** INFO ***  |   GENERAL |  building program with options -D BVH -D MEASURE_FULL_SPECTRUM -D MEASURE_MIN_LAMBDA=400 -D MEASURE_MAX_LAMBDA=700 -D MEASURE_SPECTRUM_BINS=60 -D SPECTRAL -D ENABLE_SENSORS -D SPECTRAL_WAVELENGTH_MIN=400 -D SPECTRAL_WAVELENGTH_MAX=700 -D SPECTRAL_WAVELENGTH_BINS=300 -D CL_KHR_BYTE_ADDRESSABLE_STORE -D CL_KHR_GLOBAL_INT32_BASE_ATOMICS -D CL_KHR_GLOBAL_INT32_EXTENDED_ATOMICS -D CL_KHR_LOCAL_INT32_BASE_ATOMICS -D CL_KHR_LOCAL_INT32_EXTENDED_ATOMICS -D CL_KHR_3D_IMAGE_WRITES -D CL_KHR_SPIR -D CL_KHR_FP64 -D CL_KHR_INT64_BASE_ATOMICS -D CL_KHR_INT64_EXTENDED_ATOMICS -D CL_KHR_FP64 -Werror
[2019-01-15 17:23:58.119113869] POCL: in fn compile_and_link_program at line 566:
  *** INFO ***  |   GENERAL |  building from sources for device 0
[2019-01-15 17:23:58.156086884] POCL: in fn int pocl_llvm_build_program(cl_program, unsigned int, const char*, char*, cl_uint, _cl_program* const*, const char**, int) at line 333:
  *** INFO ***  |      LLVM |  all build options: -Dcl_khr_byte_addressable_store -Dcl_khr_global_int32_base_atomics -Dcl_khr_global_int32_extended_atomics -Dcl_khr_local_int32_base_atomics -Dcl_khr_local_int32_extended_atomics -Dcl_khr_3d_image_writes -Dcl_khr_spir -Dcl_khr_fp64 -Dcl_khr_int64_base_atomics -Dcl_khr_int64_extended_atomics -Dcl_khr_fp64 -cl-ext=-all,+cl_khr_byte_addressable_store,+cl_khr_global_int32_base_atomics,+cl_khr_global_int32_extended_atomics,+cl_khr_local_int32_base_atomics,+cl_khr_local_int32_extended_atomics,+cl_khr_3d_image_writes,+cl_khr_spir,+cl_khr_fp64,+cl_khr_int64_base_atomics,+cl_khr_int64_extended_atomics,+cl_khr_fp64 -Dcl_khr_int64 -xcl -Dinline= -I. -cl-kernel-arg-info -D BVH -D MEASURE_FULL_SPECTRUM -D MEASURE_MIN_LAMBDA=400 -D MEASURE_MAX_LAMBDA=700 -D MEASURE_SPECTRUM_BINS=60 -D SPECTRAL -D ENABLE_SENSORS -D SPECTRAL_WAVELENGTH_MIN=400 -D SPECTRAL_WAVELENGTH_MAX=700 -D SPECTRAL_WAVELENGTH_BINS=300 -D CL_KHR_BYTE_ADDRESSABLE_STORE -D CL_KHR_GLOBAL_INT32_BASE_ATOMICS -D CL_KHR_GLOBAL_INT32_EXTENDED_ATOMICS -D CL_KHR_LOCAL_INT32_BASE_ATOMICS -D CL_KHR_LOCAL_INT32_EXTENDED_ATOMICS -D CL_KHR_3D_IMAGE_WRITES -D CL_KHR_SPIR -D CL_KHR_FP64 -D CL_KHR_INT64_BASE_ATOMICS -D CL_KHR_INT64_EXTENDED_ATOMICS -D CL_KHR_FP64 -Werror -D__ENDIAN_LITTLE__=1 -D__IMAGE_SUPPORT__=1 -DCL_DEVICE_MAX_GLOBAL_VARIABLE_SIZE=0 -D__OPENCL_VERSION__=120 -cl-std=CL1.2 -D__OPENCL_C_VERSION__=120 -fno-builtin -triple=x86_64-unknown-linux-gnu -target-cpu skylake-avx512
[2019-01-15 17:23:58.796681802] POCL: in fn llvm::Module* kernel_library(cl_device_id) at line 857:
  *** INFO ***  |      LLVM |  Using /user/gent/myuser/software/pocl/1.2-GCC-7.3.0-2.30/share/pocl/kernel-x86_64-unknown-linux-gnu-skylake-avx512.bc as the built-in lib.
[2019-01-15 17:23:59.402218681] POCL: in fn int pocl_llvm_build_program(cl_program, unsigned int, const char*, char*, cl_uint, _cl_program* const*, const char**, int) at line 565:
  *** INFO ***  |      LLVM |  Writing program.bc to /user/gent/myuser/.cache/pocl/kcache/NJ/HCMIGOMMFJBBFKELPMFJBACMCIIONBEEEANKJ/program.bc.
[2019-01-15 17:24:00.879513287] POCL: in fn llvm_codegen at line 171:
  *** INFO ***  |      LLVM |  Writing code gen output to /user/gent/myuser/.cache/pocl/kcache/tempfile-60-fb-8f-43-d9.so.o.
[2019-01-15 17:24:00.879529265] POCL: in fn llvm_codegen at line 181:
  *** INFO ***  |      LLVM |  written kernel.so.o size 83632
[2019-01-15 17:24:00.879885881] POCL: in fn llvm_codegen at line 195:
  *** INFO ***  |      LLVM |  Temporary kernel.so file for kernel compute : /user/gent/myuser/.cache/pocl/kcache/tempfile-3a-de-e1-81-34.so
[2019-01-15 17:24:00.879894263] POCL: in fn llvm_codegen at line 197:
  *** INFO ***  |   GENERAL |  Linking final module
[2019-01-15 17:24:00.879909263] POCL: in fn pocl_run_command at line 1056:
  *** INFO ***  |   GENERAL |  Launching: /user/gent/myuser/software/binutils/2.30-GCCcore-7.3.0/bin/ld
/user/gent/myuser/software/binutils/2.30-GCCcore-7.3.0/bin/ld: /user/gent/myuser/.cache/pocl/kcache/tempfile-60-fb-8f-43-d9.so.o: relocation R_X86_64_32S against `.rodata.cst4' can not be used when making a shared object; recompile with -fPIC
/user/gent/myuser/software/binutils/2.30-GCCcore-7.3.0/bin/ld: final link failed: Nonrepresentable section on output
[2019-01-15 17:24:00.895374446] POCL: in fn llvm_codegen at line 222:
  *** INFO ***  |      LLVM |  Linking kernel.so.o -> kernel.so has failed
[2019-01-15 17:24:00.897948787] POCL: in fn llvm_codegen at line 254:
  *** INFO ***  |    TIMING |       >>>         1.466430665  s    API: llvm_codegen
[2019-01-15 17:24:00.897960781] POCL: in fn pocl_check_dlhandle_cache at line 968:
  *** INFO ***  |   GENERAL |  Using static WG size binary: (null)
Final linking of kernel compute failed.
```

I can easily reproduce the relocation error manually afterwards by manually trying to link the `kernel.so`:

```
$ /user/gent/myuser/software/binutils/2.30-GCCcore-7.3.0/bin/ld -o kernel.so /user/gent/myuser/.cache/pocl/kcache/tempfile-60-fb-8f-43-d9.so.o -shared -lm
/user/gent/myuser/software/binutils/2.30-GCCcore-7.3.0/bin/ld: /user/gent/myuser/.cache/pocl/kcache/tempfile-0b-15-b8-e7-ec.so.o: relocation R_X86_64_32S against `.rodata.cst4' can not be used when making a shared object; recompile with -fPIC
/user/gent/myuser/software/binutils/2.30-GCCcore-7.3.0/bin/ld: final link failed: Nonrepresentable section on output
```

I spent several hours debugging this issue trying to find the culprit, to find out in the end that this problem does not present itself when using Clang 6.0.1 (or 6.0.0), even though that was built (from source) in the exact same way as Clang 7.0.1 (or 7.0.0, same problem).

Any idea what may be the cause of this?
Has some default been changed in Clang 7.0.x, or is this a bug in Clang 7.0.1?

I'm unsure how to trim this down further to a minimal test case to report the bug to Clang...

**Comment by pjaaskel** [comment]
I have seen this, IIRC it was due to clang producing reloc types the too old ld of that Ubuntu version did not understand. I cannot remember how to workaround it though. It might be worthwhile searching also elsewhere as it should be a more general issue, also LLVM bugzilla could have something.

**Comment by boegel** [comment]
@pjaaskel In this case, I'm using a fairly recent `ld` versions though (via a self-built `binutils` 2.30), so I doubt this would be too old for Clang 7.0.x (but I'll take a look around, I may be mistaken).

Another suspicion I had was that it could be an issue with `ld.bfd` (old-style linker) vs `ld.gold` (new-style linker), but I couldn't fix the problem using either `ld.bfd` or `ld.gold` explicitly...

**Comment by franz** [comment]
Hello,

Can i have some more information: 1) on which linux distribution did this happen, 2) cmake flags used to build Clang, 3) cmake flags to build Pocl.

Also, can you try if [this patch](https://gist.github.com/franz/d0d966d16b50c0b07fb92e9dbdef3c44) helps.

**Comment by franz** [comment]
This should be fixed in git master now, please retry

**Comment by boegel** [comment]
Sorry for not getting back to you on this earlier...

I've just tried with current master (e035a9a) and Clang 7.0.1, and I'm afraid I'm still seeing the same problem.

To answer on your questions:
* CentOS 7.6 (but with a self-built GCC 7.3.0 + binutils 2.30, not using the system compiler)
* Clang 7.0.1 built with following CMake flags:
  ```
  cmake -DCMAKE_C_COMPILER='gcc' -DCMAKE_CXX_COMPILER='g++' -DCMAKE_CXX_FLAGS='-O2 -ftree-vectorize -fno-math-errno' -DCMAKE_C_FLAGS='-O2 -ftree-vectorize -fno-math-errno' -DCMAKE_VERBOSE_MAKEFILE=ON  -DGCC_INSTALL_PREFIX='/path/to/GCC/7.3.0'  -DCMAKE_BUIL      D_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_TARGETS_TO_BUILD="X86" ...
  ```
* `pocl` CMake flags:
  ```
   cmake -DCMAKE_C_COMPILER='gcc' -DCMAKE_CXX_COMPILER='g++' -DCMAKE_CXX_FLAGS='-O2 -ftree-vectorize -fno-math-errno' -DCMAKE_C_FLAGS='-O2 -ftree-vectorize -fno-math-errno' -DCMAKE_VERBOSE_MAKEFILE=ON -DENABLE_ICD=0 -DINSTALL_OPENCL_HEADERS=1 ...
  ```

I also tried building `pocl` with `-fPIC` added to the C/CXX flags, but that doesn't make any difference...

**Comment by pjaaskel** [comment]
Please try with the latest master and preferably with the latest supported LLVM. I think there is no one providing active support for older Clang/LLVM versions.
